openapi: 3.0.0
info:
  title: Apple products API
  description:
    Final exam
  version: 1.0.0
servers:
- url: /apple-api/v1
paths:
  /products:
    get:
      summary: Returns a list of products.
      operationId: controller.get_products
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductShort'
  /sales/{country}:
    parameters:
    - name: country
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns a list of sale of the country.
      operationId: controller.get_sales
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SalesVolume'

components:
  schemas:
    ProductShort:
      type: object
      properties:
        productId:
          type: integer
        name:
          type: string
    SalesVolume:
      type: object
      properties:
        amount:
          type: number
        country:
          type: string
